#!/usr/bin/bash

set -eoux pipefail

echo "::group::Executing install-custom-packages"
trap 'echo "::endgroup::"' EXIT

wget https://github.com/token2/token2-fido-bridge/releases/download/v0.1.3/token2-fido-bridge-0.1.3-1.fc41.x86_64.rpm
dnf5 -y install ./token2-fido-bridge-0.1.3-1.fc41.x86_64.rpm