#!/usr/bin/bash

set -eoux pipefail

echo "::group::Executing install-kernel-akmods-sb"
trap 'echo "::endgroup::"' EXIT

#/ctx/install-kmods \
#    /tmp/rpms/{common,kmods}/*kvmfr*.rpm \
#    /tmp/rpms/{common,kmods}/*openrazer*.rpm \
#    /tmp/rpms/{common,kmods}/*v4l2loopback*.rpm \
#    /tmp/rpms/{common,kmods}/*xone*.rpm \
#    /tmp/rpms/{common,kmods}/*wl*.rpm

/ctx/install-kmods \
    /tmp/rpms/{extra,kmods-extra}/*zenergy*.rpm \
    /tmp/rpms/{extra,kmods-extra}/*ryzen_smu*.rpm
